default[:pkg_build][:nginx][:version] = nil
default[:pkg_build][:nginx][:versions] = nil
default[:pkg_build][:nginx][:pkg_dependencies] = %w(libpcre3 libpcre3-dev libssl-dev)
default[:pkg_build][:nginx][:base_uri] = 'http://nginx.org/download' #filename nginx-1.6.2.tar.gz
default[:pkg_build][:nginx][:build_dir] = '/var/cache/nginx'
default[:pkg_build][:nginx][:sbin_path_prefix] = '/usr'
default[:pkg_build][:nginx][:sbin_path] = "#{node[:pkg_build][:nginx][:sbin_path_prefix]}/sbin/nginx"
default[:pkg_build][:nginx][:conf_path] = '/etc/nginx/nginx.conf'
default[:pkg_build][:nginx][:pid_dir] = '/var/run'
default[:pkg_build][:nginx][:pid_file] = 'nginx.pid'
default[:pkg_build][:nginx][:lock_path] = '/var/lock/nginx.lock'
default[:pkg_build][:nginx][:error_log_path] = '/var/log/nginx/error.log'
default[:pkg_build][:nginx][:http_log_path] = '/var/log/nginx/access.log'
default[:pkg_build][:nginx][:http_client_body_temp_path] = '/var/tmp/nginx/client'
default[:pkg_build][:nginx][:http_proxy_temp_path] = '/var/tmp/nginx/proxy'
default[:pkg_build][:nginx][:http_fastcgi_temp_path] = '/var/tmp/nginx/fastcgi'
default[:pkg_build][:nginx][:additional_compile_options] = '--with-http_spdy_module --with-ipv6 --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module'
default[:pkg_build][:nginx][:user] = 'www-data'
default[:pkg_build][:nginx][:group] = 'www-data'
